name: Build Supermodel

on:
  workflow_dispatch:  # Manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
       repository: aerisarn/Supermodel-uwp-gl
  
    - name: Install MSYS2 and dependencies
      run: |
       choco install msys2 -y
       bash -lc "pacman -Syuu --noconfirm"
       bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net"  
       
    - name: Set up MSYS2 environment variables
      run: |
        echo "::add-path::C:\\msys64\\mingw64\\bin"
        RefreshEnv

    - name: Build Supermodel without network support
      run: mingw32-make -f Makefiles/Makefile.Win32

    # If you want to build with network support, uncomment the following lines:
    #- name: Build Supermodel with network support
    #  run: mingw32-make -f Makefiles/Makefile.Win32 NET_BOARD=1
